spring.application.name=2team
server.servlet.context-path=/
server.port=8080

# ========== MySQL ==========
spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.jdbc-url=${DB_URL}
spring.datasource.hikari.username=${DB_USERNAME}
spring.datasource.hikari.password=${DB_PASSWORD}
spring.datasource.hikari.pool-name=hikari-pool

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# ========== MyBatis ==========
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.ureca.ureca.domain.**.dto
mybatis.configuration.map-underscore-to-camel-case=true


# ========== swagger ==========
springdoc.packages-to-scan=com.ureca.ureca.domain
springdoc.paths-to-match=/api/**
springdoc.default-consumes-media-type=application/json;charset=UTF-8
springdoc.default-produces-media-type=application/json;charset=UTF-8
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.groups.enabled=true
springdoc.cache.disabled=true

firebase.credentials-resource=classpath:firebase/firebase-service-account.json
clova.speech.secret=${CLOVA_SPEECH_SECRET}
clova.speech.invoke-url=${CLOVA_SPEECH_INVOKE_URL}

#=========== gemini ===========
# Gemini API
gemini.baseurl=https://generativelanguage.googleapis.com
gemini.api.key=${GEMINI_API_KEY}
