SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  firebase_uid VARCHAR(128) NOT NULL UNIQUE AFTER id,
  photo_url VARCHAR(500) NULL AFTER name,
  last_login_at TIMESTAMP NULL AFTER created_at,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
